
spring:
  mvc:
    log-resolved-exception: true

  jpa:
    show-sql: true
    database: POSTGRESQL
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        generate_statistics: false
      format_sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: 'validate'

  datasource:
    url: jdbc:postgresql://localhost:5432/app-test?createDatabaseIfNotExist=true
    username: postgres
    password: paskal123
    driver-class-name: org.postgresql.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 1
      max-active: 5

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 10000
      pool-name: db-connection-pool
      connection-test-query: SELECT 1

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  liquibase:
    enabled: true
    change-log: classpath:liquibase\db\changelog\t01-local\db.changelog-master.yaml

  boot:
    admin:
      client:
        enabled: false
  jmx:
    enabled: false

  application:
    admin:
      enabled: false

  sql:
    init:
      platform: postgres
      mode: never
      data-locations: classpath*:archive/legacy-data/data-postgres.sql

management:
  endpoint:
    info:
      enabled: false
    shutdown:
      enabled: false
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        exclude: "*"

access_token_private_key_path: "access-refresh-token-keys/access-token-private.key"
access_token_public_key_path: "access-refresh-token-keys/access-token-public.key"
refresh_token_private_key_path: "access-refresh-token-keys/refresh-token-private.key"
refresh_token_public_key_path: "access-refresh-token-keys/refresh-token-public.key"

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE